[package]
name = "yewbulma"
version = "0.1.0"
authors = ["Filip Bucek <fbucek@invloop.cz>"]
edition = "2018"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
log = "0.4"
console_log = "0.2"
anyhow = "1"
# serde = { version = "1.0", features = ["rc"] }
serde_derive = "1"
serde_yaml = "0.8"
serde_json = "1.0"
yew = { version = "0.14", features = ["web_sys"] }
yew-router = { version = "0.11", features = ["web_sys"]}
regex = "1.3"
wee_alloc = "0.4"
#pulldown-cmark = "0.1.2"


# [profile.release]
# panic = 'abort' 
# codegen-units = 1 
# # default 147 kB (gzipped) 
# opt-level = 'z' # 120 kB (gzipped) optimize for size more aggressively
# # opt-level = 's' # 128 kB (gzipped) optimize fof size 
# lto = true 

[dev-dependencies]
wasm-bindgen-test = "0.3"
